default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  host: db
  user: postgres
  password: agreatpassword

development:
  <<: *default
  database: credence_goods_development


test:
  <<: *default
  database: credence_goods_test
